<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank Card</title>
    <link rel="stylesheet" href="card.css" type="text/css">

</head>

<body>
<div class="card">
    <div class="bank-name">Money Bank</div>
    <div class="logo">
        <img src="mastercard.png" alt="Mastercard Logo">
    </div>
    <div class="card-details">
        <div class="card-number">1234 5678 9012 3456</div>
        <div class="expiry-date">12/23</div>
        <div class="cardholder-name">John Doe</div>
    </div>
    <img class="chip" src="chip.png" alt="Chip">
</div>

</body>
</html>
